name: Check issue works

on:
  workflow_dispatch:


jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Failed
      run: |
        echo "logging" > scrapy.log
        exit 2

    - name: Attach log
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: scrapy.log
        path: scrapy.log

  debug:
    needs: [scheduled]
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    permissions:
      issues: write

    steps:

    - name: Get current date in NOW env variable
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Report issue on failure
      env:
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        gh issue create --title "Failed job $NOW" --assignee "$GITHUB_REPOSITORY_OWNER" --body "$RUN_URL"
